# Generated by Django 4.2.25 on 2025-10-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_alter_post_options_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[{'Draft', 'D'}, {'P', 'Published'}], default='D', max_length=10),
        ),
    ]
